General cleanup

diff --git a/scripts/markdownify b/scripts/markdownify
--- a/scripts/markdownify
+++ b/scripts/markdownify
@@ -2,47 +2,47 @@
 
 FILE="$1"
 if [ "$FILE" = "" ]; then
-	echo "missing argument"
-	exit 1
+    echo "missing argument"
+    exit 1
 fi
 
 cat <<EOF
 <html>
 <head>
-	<title>$FILE</title>
-	<style type="text/css">
-		body {
-			margin: 3em 5em;
-			font-family: Helvetica, sans-serif;
-			font-size: 16px;
-		}
-		code {
-			font-family: Menlo, Monaco, "Courier New", monospace;
-			font-size: 14px;
-		}
-		p code, li code, pre {
-			border: 1px solid #bbbbbb;
-			background-color: #eeeeee;
-		}
-		p code, li code {
-			margin: 0px 2px;
-			padding: 0px 2px;
-		}
-		pre {
-			margin: 0px 0px;
-			padding: 2px 5px;
-		}
-		a, a:visited {
-			text-decoration: underline;
-			color: blue;
-		}
-		a:hover, a:active {
-			color: red;
-		}
-		#main {
-			width: 40em;
-		}
-	</style>
+    <title>$FILE</title>
+    <style type="text/css">
+        body {
+            margin: 3em 5em;
+            font-family: Helvetica, sans-serif;
+            font-size: 16px;
+        }
+        code {
+            font-family: Menlo, Monaco, "Courier New", monospace;
+            font-size: 14px;
+        }
+        p code, li code, pre {
+            border: 1px solid #bbbbbb;
+            background-color: #eeeeee;
+        }
+        p code, li code {
+            margin: 0px 2px;
+            padding: 0px 2px;
+        }
+        pre {
+            margin: 0px 0px;
+            padding: 2px 5px;
+        }
+        a, a:visited {
+            text-decoration: underline;
+            color: blue;
+        }
+        a:hover, a:active {
+            color: red;
+        }
+        #main {
+            width: 40em;
+        }
+    </style>
 </head>
 
 <body>
