tabs->spaces

diff --git a/bash/config b/bash/config
--- a/bash/config
+++ b/bash/config
@@ -3,97 +3,97 @@ umask 0022
 
 test -n "$INTERACTIVE" && {
 
-	# Suppress local mail notices
-	shopt -u mailwarn >/dev/null 2>&1
-	unset MAILCHECK
+    # Suppress local mail notices
+    shopt -u mailwarn >/dev/null 2>&1
+    unset MAILCHECK
 
-	# Do not try to complete when the command is empty/whitespace
-	shopt -s no_empty_cmd_completion >/dev/null 2>&1
+    # Do not try to complete when the command is empty/whitespace
+    shopt -s no_empty_cmd_completion >/dev/null 2>&1
 
-	# Append history to ~/.bash_history on shell exit
-	shopt -s histappend >/dev/null 2>&1
+    # Append history to ~/.bash_history on shell exit
+    shopt -s histappend >/dev/null 2>&1
 
-	# --------------------------------------------------------------------
-	# Prompt
-	#
-	# Bash escapes:
-	#
-	# \j    Number of jobs currently managed by the shell
-	# \n    New line
-	# \u    Username
-	# \w    Current working directory
-	# \W    Name of this directory (not full dir)
-	# \\$   $ or # (depending on uid)
-	# \[    Start of non-printing sequence (e.g. colors)
-	# \]    End of non-printing sequence
-	#
-	# Environment variables:
-	#
-	# \$?   Exit value of last command executed (eval'd on each prompt)
-	#
-	# Functions:
-	#
-	# _xc <fg_color> [<bg_color>]
-	#     Sets a foreground color, and optionally a background color.
-	#
-	# _xcb <fg_color> [<bg_color>]
-	#     Same as _xc(), but uses bold variant.
-	#
-	# _xcr
-	#     Resets to default colors.
-	#
-	# _short_hname
-	#     Returns a shortened version of local system name.
-	#
-	# _scm_info (escaped to eval on each prompt)
-	#     Looks for code repositories. If git is found, branch name is shown.
-	#     For CVS or Subversion directories, the repository type is shown.
-	#
-	# _xc_retval (escaped to eval on each prompt)
-	#     Returns a highlighted color if $? is non-zero.
-	#
-	# _xc_jobs (escaped to eval on each prompt)
-	#     Returns a highlighted color if `jobs` lists 1 or more jobs.
+    # --------------------------------------------------------------------
+    # Prompt
+    #
+    # Bash escapes:
+    #
+    # \j    Number of jobs currently managed by the shell
+    # \n    New line
+    # \u    Username
+    # \w    Current working directory
+    # \W    Name of this directory (not full dir)
+    # \\$   $ or # (depending on uid)
+    # \[    Start of non-printing sequence (e.g. colors)
+    # \]    End of non-printing sequence
+    #
+    # Environment variables:
+    #
+    # \$?   Exit value of last command executed (eval'd on each prompt)
+    #
+    # Functions:
+    #
+    # _xc <fg_color> [<bg_color>]
+    #     Sets a foreground color, and optionally a background color.
+    #
+    # _xcb <fg_color> [<bg_color>]
+    #     Same as _xc(), but uses bold variant.
+    #
+    # _xcr
+    #     Resets to default colors.
+    #
+    # _short_hname
+    #     Returns a shortened version of local system name.
+    #
+    # _scm_info (escaped to eval on each prompt)
+    #     Looks for code repositories. If git is found, branch name is shown.
+    #     For CVS or Subversion directories, the repository type is shown.
+    #
+    # _xc_retval (escaped to eval on each prompt)
+    #     Returns a highlighted color if $? is non-zero.
+    #
+    # _xc_jobs (escaped to eval on each prompt)
+    #     Returns a highlighted color if `jobs` lists 1 or more jobs.
 
-	# Reset to default colors, then start a new line
-	PS1="\[$(_xcr)\]\n"
+    # Reset to default colors, then start a new line
+    PS1="\[$(_xcr)\]\n"
 
-	# Check for new mail
-	PS1="$PS1\[$(_xc 160)\]\$(_check_for_mail)\[$(_xcr)\]"
+    # Check for new mail
+    PS1="$PS1\[$(_xc 160)\]\$(_check_for_mail)\[$(_xcr)\]"
 
-	# Show current directory in violet
-	PS1="$PS1\[$(_xc 176)\]\w\[$(_xcr)\]"
+    # Show current directory in violet
+    PS1="$PS1\[$(_xc 176)\]\w\[$(_xcr)\]"
 
-	# Show code repo info in green (if present), then start new line
-	PS1="$PS1\[$(_xc 114)\]\$(_scm_info)\[$(_xcr)\]\n"
+    # Show code repo info in green (if present), then start new line
+    PS1="$PS1\[$(_xc 114)\]\$(_scm_info)\[$(_xcr)\]\n"
 
-	# Show {user}@{host} in yellow
-	PS1="$PS1\[$(_xc 228)\]\u@$(_short_hname)\[$(_xcr)\]"
+    # Show {user}@{host} in yellow
+    PS1="$PS1\[$(_xc 228)\]\u@$(_short_hname)\[$(_xcr)\]"
 
-	# Show the value of $? in dark grey (bold red if it's non-zero)
-	PS1="$PS1\[$(_xc 241)\]{\[\$(_xc_retval)\]\$?\[$(_xc 241)\]}\[$(_xcr)\]"
+    # Show the value of $? in dark grey (bold red if it's non-zero)
+    PS1="$PS1\[$(_xc 241)\]{\[\$(_xc_retval)\]\$?\[$(_xc 241)\]}\[$(_xcr)\]"
 
-	# Show the current number of jobs (in orange if > 0)
-	PS1="$PS1\[$(_xc 241)\][\[\$(_xc_jobs)\]\j\[$(_xc 241)\]]"
+    # Show the current number of jobs (in orange if > 0)
+    PS1="$PS1\[$(_xc 241)\][\[\$(_xc_jobs)\]\j\[$(_xc 241)\]]"
 
-	# Show either a '$' or a '#' prompt, always in orange.
-	PS1="$PS1\[$(_xc 214)\]\\$\[$(_xcr)\] "
+    # Show either a '$' or a '#' prompt, always in orange.
+    PS1="$PS1\[$(_xc 214)\]\\$\[$(_xcr)\] "
 
-	export PS1
+    export PS1
 
-	# A decent tcsh prompt:
-	#set prompt = '%n@%M:%c{%?}%# '
+    # A decent tcsh prompt:
+    #set prompt = '%n@%M:%c{%?}%# '
 
-	stty erase '^?' -parenb -istrip echo echoe echoctl echoke tabs cs8
+    stty erase '^?' -parenb -istrip echo echoe echoctl echoke tabs cs8
 
-	# Use vi keybindings for commandline edits
-	set -o vi
+    # Use vi keybindings for commandline edits
+    set -o vi
 
-	# notify of bg job completion immediately
-	set -o notify
+    # notify of bg job completion immediately
+    set -o notify
 
-	# set the titlebar
-	echo -ne "\x1b]2;$HOST\x07\x1b]1;$HOST\x07"
+    # set the titlebar
+    echo -ne "\x1b]2;$HOST\x07\x1b]1;$HOST\x07"
 
 }
 
