improved prompt coloring, fixed buggy input line lengths

diff --git a/bash/config b/bash/config
--- a/bash/config
+++ b/bash/config
@@ -13,17 +13,45 @@ test -n "$INTERACTIVE" && {
 	# Append history to ~/.bash_history on shell exit
 	shopt -s histappend >/dev/null 2>&1
 
+	# --------------------------------------------------------------------
 	# Prompt
-	# See bash/functions for parse_git_branch() and other functions.
 	#
+	# Bash escapes:
+	#
+	# \j    Number of jobs currently managed by the shell
+	# \n    New line
 	# \u    Username
 	# \w    Current working directory
 	# \W    Name of this directory (not full dir)
-	# \$?   Expands to $?, i.e. exit value of last command executed
-	# \$    $ or # (depending on uid)
-	# \j    Number of jobs currently managed by the shell
+	# \\$   $ or # (depending on uid)
+	# \[    Start of non-printing sequence (e.g. colors)
+	# \]    End of non-printing sequence
 	#
-	export PS1="$(_xc_reset)\n$(_xc_bold 214)[\j]$(_xc_reset) $(_xc 176)\w$(_xc_reset)$(_xc_bold 197)\$(_git_branch)$(_xc_reset)\n$(_xc 228)\u@$(_short_hname)$(_xc_reset){\$(_color_retval)}\\$ "
+	# Environment variables:
+	#
+	# \$?   Exit value of last command executed (eval'd on each prompt)
+	#
+	# Functions:
+	#
+	# _xc <fg_color> [<bg_color>]
+	#     Sets a foreground color, and optionally a background color.
+	#
+	# _xc_bold <fg_color> [<bg_color>]
+	#     Same as _xc(), but uses bold variant.
+	#
+	# _xc_reset
+	#     Resets to default colors.
+	#
+	# _short_hname
+	#     Returns a shortened version of local system name.
+	#
+	# _git_branch (escaped to eval on each prompt)
+	#     Returns name of current branch, if inside a git repository.
+	#
+	# _retval_color (escaped to eval on each prompt)
+	#     Returns a highlighted color if $? is non-zero.
+
+	export PS1="\[$(_xc_reset)\]\n\[$(_xc_bold 214)\][\j]\[$(_xc_reset)\] \[$(_xc 176)\]\w\[$(_xc_reset)$(_xc_bold 197)\]\$(_git_branch)\[$(_xc_reset)\]\n\[$(_xc 228)\]\u@$(_short_hname)\[$(_xc_reset)\]{\[\$(_retval_color)\]\$?\[$(_xc_reset)\]}\\$ "
 
 	# A decent tcsh prompt:
 	#set prompt = '%n@%M:%c{%?}%# '
diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -1,7 +1,6 @@
 
 # "h" shows entire history
 # "h <pattern>" shows you history entries matching the string
-# ht is the same thing, but runs it through tail -20.
 function h() {
 	test -n "$1" && history | grep -i "$1" || history
 }
@@ -28,12 +27,11 @@ function astr() {
 }
 
 # Get the current git branch (for shell prompt).
-# _preserve passes through $? unmolested, both for displaying it in the prompt
-# and for using it generally.
+# Preserve the value of $? by returning it as we received it.
 function _git_branch() {
-	_preserve=$?
+	_retval=$?
 	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
-	return $_preserve
+	return $_retval
 }
 
 # Easy clone of a project that lives on Dreamhost
@@ -66,8 +64,9 @@ function gitclone_ntt() {
 # Give me a shortened version of the local hostname.
 # If it's 1-3 atoms, give me only the first.
 # If it's more than that, give me the first two.
+# Preserve the value of $? by returning it as we received it.
 function _short_hname() {
-	_preserve=$?
+	_retval=$?
 
 	echo $HOST | perl -p -e '
 		if ( scalar( split( /\./ ) ) > 3 ) {
@@ -77,47 +76,46 @@ function _short_hname() {
 		}
 	'
 
-	# Alternate version from Ravi. Much shorter, but it gives
+	# Alternate version from Ravi Pina. Much shorter, but it gives
 	# you three atoms on long names, not two, and on a single
 	# atom it doesn't return anything at all.
 	#perl -le '$ENV{HOST}=~/^((?:[^.]+\.){2}[^.]+|[^.]+)\./;print$1'
 
-	return $_preserve
+	return $_retval
 }
 
 # Output an extended color (256-color support). If one color is provided,
 # set the foreground. If two are provided, set {foreground, background}.
+# Preserve the value of $? by returning it as we received it.
 function _xc() {
-	_preserve=$?
-	echo -ne "\[\033[38;05;$1m\]"
-	test -n "$2" && echo -ne "\[\033[48;05;$2m\]"
-	return $_preserve
+	_retval=$?
+	echo -ne "\033[38;05;$1m"
+	test -n "$2" && echo -ne "\033[48;05;$2m"
+	return $_retval
 }
 
 # Make the foreground color bold instead of normal.
+# Preserve the value of $? by returning it as we received it.
 function _xc_bold() {
-	_preserve=$?
-	echo -ne "\[\033[01m\]"
+	_retval=$?
+	echo -ne "\033[01m"
 	_xc $@
-	return $_preserve
+	return $_retval
 }
 
 # Set back to normal colors.
+# Preserve the value of $? by returning it as we received it.
 function _xc_reset() {
-	_preserve=$?
-	echo -ne "\[\033[0m\]"
-	return $_preserve
+	_retval=$?
+	echo -ne "\033[0m"
+	return $_retval
 }
 
-# Give me a retval that's colorized based on its value. For some reason I have
-# to embed the escape codes directly; I can't use the _xc* functions.
-function _color_retval() {
+# Evaluate $? and return an attention-grabbing color if non-zero.
+# Preserve the original value of $? by returning it as we received it.
+function _retval_color() {
 	_retval=$?
-	if [[ $_retval == 0 ]]; then
-		echo -ne "\033[0m$_retval"
-	else
-		echo -ne "\033[1m\033[38;5;196m$_retval\033[0m"
-	fi
+	[[ $_retval != 0 ]] && echo -ne "\033[1m\033[38;5;196m"
 	return $_retval
 }
 
