formatting cleanup

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -3,64 +3,64 @@
 # "h <pattern>" shows you history entries matching the string
 # ht is the same thing, but runs it through tail -20.
 function h() {
-    test -n "$1" && history | grep -i "$1" || history
+	test -n "$1" && history | grep -i "$1" || history
 }
 
 # Look up error codes
 function errno() {
-    perl -e "\$! = $1; print \"\$! \\n\";"
+	perl -e "\$! = $1; print \"\$! \\n\";"
 }
 
 # machine type, on solaris
 function hw() {
-    [[ "$OS" != "SunOS" ]] && {
-        echo "'hw' is only available in SunOS."
-        return
-    }
-    prtdiag | head -1 | \
-        sed "s/^System Configuration: *Sun Microsystems *//" | \
-        sed "s/^`uname -m` *//"
+	[[ "$OS" != "SunOS" ]] && {
+		echo "'hw' is only available in SunOS."
+		return
+	}
+	prtdiag | head -1 | \
+		sed "s/^System Configuration: *Sun Microsystems *//" | \
+		sed "s/^`uname -m` *//"
 }
 
 # Translate AS numbers / RR communities
 function astr() {
-    echo "$1" | tr '[A-J0-9]' '[0-9A-J]'
+	echo "$1" | tr '[A-J0-9]' '[0-9A-J]'
 }
 
 # Get the current git branch (for shell prompt).
 # _preserve passes through $? unmolested, both for displaying it in the prompt
 # and for using it generally.
 function _git_branch() {
-    _preserve=$?
-    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
-    return $_preserve
+	_preserve=$?
+	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
+	return $_preserve
 }
 
 # Easy clone of a project that lives on Dreamhost
 function gitclone_dreamhost() {
-    _user="scsiboy"
-    _server="git.tangledhelix.com"
+	_user="scsiboy"
+	_server="git.tangledhelix.com"
 
-    test -n "$1" || {
-        echo "Missing argument (repo to clone)"
-        return
-    }
+	test -n "$1" || {
+		echo "Missing argument (repo to clone)"
+		return
+	}
 
-    git clone ssh://$_user@$_server/~/git/$1 $2
+	git clone ssh://$_user@$_server/~/git/$1 $2
 }
 
 # NTT git environment is a little weird, streamline it.
 function gitclone_ntt() {
-    _path="/usr/local/bin/git-upload-pack"
-    _user="dan"
-    _server="admin1.mlpsca01.us.to.gin.ntt.net"
+	_path="/usr/local/bin/git-upload-pack"
+	_user="dan"
+	_server="admin1.mlpsca01.us.to.gin.ntt.net"
 
-    test -n "$1" || {
-        echo "Missing argument (repo to clone)"
-        return
-    }
+	test -n "$1" || {
+		echo "Missing argument (repo to clone)"
+		return
+	}
 
-    git clone -o ntt -u $_path ssh://$_user@$_server/~/git/$1 $2
+	git clone -o ntt -u $_path ssh://$_user@$_server/~/git/$1 $2
 }
 
 # Give me a shortened version of the local hostname.
@@ -68,18 +68,18 @@ function gitclone_ntt() {
 # If it's more than that, give me the first two.
 function _short_hname() {
 
-    echo $HOST | perl -p -e '
-        if ( scalar( split( /\./ ) ) > 3 ) {
-            s/^([^.]+\.[^.]+).*$/$1/;
-        } else {
-            s/^([^.]+).*$/$1/;
-        }
-    '
+	echo $HOST | perl -p -e '
+		if ( scalar( split( /\./ ) ) > 3 ) {
+			s/^([^.]+\.[^.]+).*$/$1/;
+		} else {
+			s/^([^.]+).*$/$1/;
+		}
+	'
 
-    # Alternate version from Ravi. Much shorter, but it gives
-    # you three atoms on long names, not two, and on a single
-    # atom it doesn't return anything at all.
-    #perl -le '$ENV{HOST}=~/^((?:[^.]+\.){2}[^.]+|[^.]+)\./;print$1'
+	# Alternate version from Ravi. Much shorter, but it gives
+	# you three atoms on long names, not two, and on a single
+	# atom it doesn't return anything at all.
+	#perl -le '$ENV{HOST}=~/^((?:[^.]+\.){2}[^.]+|[^.]+)\./;print$1'
 
 }
 
@@ -96,7 +96,7 @@ function _xc() {
 function _xc_bold() {
 	_preserve=$?
 	echo -ne "\[\033[01m\]"
-	_xcolor $@
+	_xc $@
 	return $_preserve
 }
 
@@ -108,7 +108,7 @@ function _xc_reset() {
 }
 
 # Give me a retval that's colorized based on its value. For some reason I have
-# to embed the escape codes directly; I can't use the _xcolor function.
+# to embed the escape codes directly; I can't use the _xc function.
 function _color_retval() {
 	_retval=$?
 	if [[ $_retval == 0 ]]; then
diff --git a/bash/project-mgmt b/bash/project-mgmt
--- a/bash/project-mgmt
+++ b/bash/project-mgmt
@@ -1,109 +1,109 @@
 
 test -n "$INTERACTIVE" && {
 
-    # This will create a project directory with the current date and a label,
-    # e.g. 20100904-openssh-upgrade. Optionally supply a ticket number to be
-    # inserted after the date, e.g. 20100904-29714-openssh-upgrade.
+	# This will create a project directory with the current date and a label,
+	# e.g. 20100904-openssh-upgrade. Optionally supply a ticket number to be
+	# inserted after the date, e.g. 20100904-29714-openssh-upgrade.
 
-    mkproj() {
-        _usage="Usage: mkproj <description> [<ticket>]"
+	mkproj() {
+		_usage="Usage: mkproj <description> [<ticket>]"
 
-        if [[ "$1" = "-h" ]]; then
-            echo $_usage
-            return
-        fi
+		if [[ "$1" = "-h" ]]; then
+			echo $_usage
+			return
+		fi
 
-        _date=`date +"%Y%m%d"`
+		_date=`date +"%Y%m%d"`
 
-        if test -n "$2"; then
-            _projdir="$_date-$2-$1"
-        elif test -n "$1"; then
-            _projdir="$_date-$1"
-        else
-            echo $_usage
-            return
-        fi
+		if test -n "$2"; then
+			_projdir="$_date-$2-$1"
+		elif test -n "$1"; then
+			_projdir="$_date-$1"
+		else
+			echo $_usage
+			return
+		fi
 
-        mkdir ~/$_projdir && cd ~/$_projdir
-    }
+		mkdir ~/$_projdir && cd ~/$_projdir
+	}
 
-    # Find a project. If only one project matches, just go there.
-    # If multiple do, print a list for me to select from. Hit enter to
-    # choose the last option automatically.
-    #
-    # If this doesn't work, SUNWxcu4 probably needs to be installed.
+	# Find a project. If only one project matches, just go there.
+	# If multiple do, print a list for me to select from. Hit enter to
+	# choose the last option automatically.
+	#
+	# If this doesn't work, SUNWxcu4 probably needs to be installed.
 
-    proj() {
+	proj() {
 
-        test -x /usr/xpg4/bin/awk && _awk="/usr/xpg4/bin/awk" || _awk="awk"
+		test -x /usr/xpg4/bin/awk && _awk="/usr/xpg4/bin/awk" || _awk="awk"
 
-        # need to use a specific path to ls because the color ls
-        # aliases break the awk parsing
-        _ls="/bin/ls"
+		# need to use a specific path to ls because the color ls
+		# aliases break the awk parsing
+		_ls="/bin/ls"
 
-        if [[ "$1" = "-h" ]]; then
-            echo "Usage: proj <pattern>"
-            return
-        fi
+		if [[ "$1" = "-h" ]]; then
+			echo "Usage: proj <pattern>"
+			return
+		fi
 
-        cd ~
+		cd ~
 
-        # if no pattern is given, go to the newest project (by mtime).
-        test -z "$1" && {
-            _newest=`$_ls -ltr|$_awk '/^d/ {if ($9~/^[0-9]{8}-/) {print $9}}'|tail -1`
-            test -d $_newest && cd $_newest || echo "No match."
-            return
-        }
+		# if no pattern is given, go to the newest project (by mtime).
+		test -z "$1" && {
+			_newest=`$_ls -ltr|$_awk '/^d/ {if ($9~/^[0-9]{8}-/) {print $9}}'|tail -1`
+			test -d $_newest && cd $_newest || echo "No match."
+			return
+		}
 
-        # Get a count of projects (by pattern match).
-        _projcount="`$_ls -ltr|$_awk '/^d/ {if (\$9~/^[0-9]{8}-/) {print \$9}}'|grep -ci \"$1\"`"
+		# Get a count of projects (by pattern match).
+		_projcount="`$_ls -ltr|$_awk '/^d/ {if (\$9~/^[0-9]{8}-/) {print \$9}}'|grep -ci \"$1\"`"
 
-        # Case 1: there aren't any.
-        if [[ $_projcount -eq 0 ]]; then
-            echo "No match."
-            return
+		# Case 1: there aren't any.
+		if [[ $_projcount -eq 0 ]]; then
+			echo "No match."
+			return
 
-        # Case 2: there's only one. Go there automatically.
-        elif [[ $_projcount -eq 1 ]]; then
-            _dir=`$_ls -ltr|$_awk '/^d/ {if ($9~/^[0-9]{8}-/) {print $9}}'|grep -i "$1"`
-            test -d $_dir && cd $_dir || echo "Error: not a directory."
+		# Case 2: there's only one. Go there automatically.
+		elif [[ $_projcount -eq 1 ]]; then
+			_dir=`$_ls -ltr|$_awk '/^d/ {if ($9~/^[0-9]{8}-/) {print $9}}'|grep -i "$1"`
+			test -d $_dir && cd $_dir || echo "Error: not a directory."
 
-        # Case 3: it's not 0 or 1. Go over them and let me pick from a menu.
-        else
+		# Case 3: it's not 0 or 1. Go over them and let me pick from a menu.
+		else
 
-            # Build an array of found projects in _projlist. Starts at 1, not 0.
-            _counter=1
-            for _this in `$_ls -ltr|$_awk '/^d/ {if ($9~/^[0-9]{8}-/) {print $9}}'|grep -i "$1"`; do
-                _projlist[$_counter]="$_this"
-                _counter=$((_counter + 1))
-            done
+			# Build an array of found projects in _projlist. Starts at 1, not 0.
+			_counter=1
+			for _this in `$_ls -ltr|$_awk '/^d/ {if ($9~/^[0-9]{8}-/) {print $9}}'|grep -i "$1"`; do
+				_projlist[$_counter]="$_this"
+				_counter=$((_counter + 1))
+			done
 
-            # Print out a menu of choices
-            _counter=1
-            for _this in ${_projlist[@]}; do
-                echo "[$_counter] $_this"
-                _counter=$((_counter + 1))
-            done
+			# Print out a menu of choices
+			_counter=1
+			for _this in ${_projlist[@]}; do
+				echo "[$_counter] $_this"
+				_counter=$((_counter + 1))
+			done
 
-            # Collect the choice. No choice means "go to last displayed option".
-            echo -n "=> "
-            read _choice
+			# Collect the choice. No choice means "go to last displayed option".
+			echo -n "=> "
+			read _choice
 
-            # If the answer was null, back off one from the counter
-            test -z "$_choice" && _choice=$((_counter - 1))
+			# If the answer was null, back off one from the counter
+			test -z "$_choice" && _choice=$((_counter - 1))
 
-            if [[ $_choice -lt 1 ]]; then
-                echo "Out of range"
-                return
-            fi
-            if [[ -z "${_projlist[$_choice]}" ]]; then
-                echo "Out of range"
-                return
-            fi
+			if [[ $_choice -lt 1 ]]; then
+				echo "Out of range"
+				return
+			fi
+			if [[ -z "${_projlist[$_choice]}" ]]; then
+				echo "Out of range"
+				return
+			fi
 
-            _dir=${_projlist[$_choice]}
-            test -d $_dir && cd $_dir || echo "Error: not a directory."
-        fi
-    }
+			_dir=${_projlist[$_choice]}
+			test -d $_dir && cd $_dir || echo "Error: not a directory."
+		fi
+	}
 }
 
