256 color support

diff --git a/bash/library b/bash/library
--- a/bash/library
+++ b/bash/library
@@ -8,41 +8,41 @@
 # 
 # Examples:
 #
-#   yn y "Do you want to continue?" || exit
-#   yn n "Remove $FILE?" && rm -f $FILE
+# yn y "Do you want to continue?" || exit
+# yn n "Remove $FILE?" && rm -f $FILE
 
 yn() {
-    _default="$1"
-    _question="$2"
+	_default="$1"
+	_question="$2"
 
-    test -z "$_question" && {
-        echo "ERROR: yn() is missing an argument"
-        exit
-    }
+	test -z "$_question" && {
+		echo "ERROR: yn() is missing an argument"
+		exit
+	}
 
-    echo -n "$_question "
+	echo -n "$_question "
 
-    if [[ "$_default" = "y" || "$_default" = "Y" ]]; then
-        echo -n "[Y/n] "
-    elif [[ "$_default" = "n" || "$_default" = "N" ]]; then
-        echo -n "[y/N] "
-    else
-        echo "ERROR: Invalid default for yn()"
-        exit
-    fi
-    
-    read _choice
+	if [[ "$_default" = "y" || "$_default" = "Y" ]]; then
+		echo -n "[Y/n] "
+	elif [[ "$_default" = "n" || "$_default" = "N" ]]; then
+		echo -n "[y/N] "
+	else
+		echo "ERROR: Invalid default for yn()"
+		exit
+	fi
+	
+	read _choice
 
-    test -z "$_choice" && _choice=$_default
+	test -z "$_choice" && _choice=$_default
 
-    if [[ "$_choice" = "y" || "$_choice" = "Y" ]]; then
-        return 0
-    elif [[ "$_choice" = "n" || "$_choice" = "N" ]]; then
-        return 1
-    else
-        echo "Invalid choice."
-        exit
-    fi
+	if [[ "$_choice" = "y" || "$_choice" = "Y" ]]; then
+		return 0
+	elif [[ "$_choice" = "n" || "$_choice" = "N" ]]; then
+		return 1
+	else
+		echo "Invalid choice."
+		exit
+	fi
 
 }
 
